//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DS3ConnectionInfo {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UsePingFilter {
            get {
                return ((bool)(this["UsePingFilter"]));
            }
            set {
                this["UsePingFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double MaxAvgPing {
            get {
                return ((double)(this["MaxAvgPing"]));
            }
            set {
                this["MaxAvgPing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int REOHotkey {
            get {
                return ((int)(this["REOHotkey"]));
            }
            set {
                this["REOHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RSDHotkey {
            get {
                return ((int)(this["RSDHotkey"]));
            }
            set {
                this["RSDHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WSDHotkey {
            get {
                return ((int)(this["WSDHotkey"]));
            }
            set {
                this["WSDHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LeaveSessionHotkey {
            get {
                return ((int)(this["LeaveSessionHotkey"]));
            }
            set {
                this["LeaveSessionHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double SamplingDelay {
            get {
                return ((double)(this["SamplingDelay"]));
            }
            set {
                this["SamplingDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double SamplingPeriod {
            get {
                return ((double)(this["SamplingPeriod"]));
            }
            set {
                this["SamplingPeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisplayOverlay {
            get {
                return ((bool)(this["DisplayOverlay"]));
            }
            set {
                this["DisplayOverlay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OverlayHotkey {
            get {
                return ((int)(this["OverlayHotkey"]));
            }
            set {
                this["OverlayHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BorderlessMode {
            get {
                return ((bool)(this["BorderlessMode"]));
            }
            set {
                this["BorderlessMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BorderlessHotkey {
            get {
                return ((int)(this["BorderlessHotkey"]));
            }
            set {
                this["BorderlessHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OverlayAnchor {
            get {
                return ((int)(this["OverlayAnchor"]));
            }
            set {
                this["OverlayAnchor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.025")]
        public double XOffset {
            get {
                return ((double)(this["XOffset"]));
            }
            set {
                this["XOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.05")]
        public double YOffset {
            get {
                return ((double)(this["YOffset"]));
            }
            set {
                this["YOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI, 20.25pt")]
        public string OverlayFont {
            get {
                return ((string)(this["OverlayFont"]));
            }
            set {
                this["OverlayFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{SteamName} ({CharName})")]
        public string NameFormat {
            get {
                return ((string)(this["NameFormat"]));
            }
            set {
                this["NameFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{SteamName}")]
        public string NameFormatConnecting {
            get {
                return ((string)(this["NameFormatConnecting"]));
            }
            set {
                this["NameFormatConnecting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowRegion {
            get {
                return ((bool)(this["ShowRegion"]));
            }
            set {
                this["ShowRegion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public string TextColor {
            get {
                return ((string)(this["TextColor"]));
            }
            set {
                this["TextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public string OutlineColor {
            get {
                return ((string)(this["OutlineColor"]));
            }
            set {
                this["OutlineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double OutlineThickness {
            get {
                return ((double)(this["OutlineThickness"]));
            }
            set {
                this["OutlineThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFA500")]
        public string ConnectingColor {
            get {
                return ((string)(this["ConnectingColor"]));
            }
            set {
                this["ConnectingColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF00BFFF")]
        public string PingColor1 {
            get {
                return ((string)(this["PingColor1"]));
            }
            set {
                this["PingColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF7CFC00")]
        public string PingColor2 {
            get {
                return ((string)(this["PingColor2"]));
            }
            set {
                this["PingColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFF00")]
        public string PingColor3 {
            get {
                return ((string)(this["PingColor3"]));
            }
            set {
                this["PingColor3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFCD5C5C")]
        public string PingColor4 {
            get {
                return ((string)(this["PingColor4"]));
            }
            set {
                this["PingColor4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PingFilterHotkey {
            get {
                return ((int)(this["PingFilterHotkey"]));
            }
            set {
                this["PingFilterHotkey"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>The slot this player occupies in the game's SessionInfo structure.</string>
  <string>The player's in-game character name.</string>
  <string>The player's in-game team (e.g. Host, Dark Spirit, etc.)</string>
  <string>The player's Steam profile name.</string>
  <string>A combination of the player's Steam and in-game name, formatted according to overlay settings.</string>
  <string>The player's Steam ID 64 (number found in a Steam profile link).</string>
  <string>The player's ping (roundtrip time latency), calculated using the delay between sent and recieved STUN packets. Displayed in milliseconds.</string>
  <string>The player's average ping over the last 10 recieved STUN packets. Displayed in milliseconds.</string>
  <string>The standard deviation of the player's ping over the last 10 samples. A high value indicates an unstable connection. Displayed in milliseconds.</string>
  <string>The ratio of late vs. on time STUN reply packets from the player, as a percentage. Another indicator of connection quality.</string>
  <string>The state and country of the player, if available.</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SessColumnDescs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SessColumnDescs"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Visible</string>
  <string>Visible</string>
  <string>Visible</string>
  <string>Visible</string>
  <string>Hidden</string>
  <string>Hidden</string>
  <string>Visible</string>
  <string>Hidden</string>
  <string>Visible</string>
  <string>Hidden</string>
  <string>Visible</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SessColumnVisibility {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SessColumnVisibility"]));
            }
            set {
                this["SessColumnVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Hidden</string>
  <string>Hidden</string>
  <string>Hidden</string>
  <string>Hidden</string>
  <string>Visible</string>
  <string>Hidden</string>
  <string>Visible</string>
  <string>Hidden</string>
  <string>Visible</string>
  <string>Hidden</string>
  <string>Hidden</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection OverlayColVisibility {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OverlayColVisibility"]));
            }
            set {
                this["OverlayColVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public double MaxAbsPing {
            get {
                return ((double)(this["MaxAbsPing"]));
            }
            set {
                this["MaxAbsPing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SpamRedEyeOrb {
            get {
                return ((bool)(this["SpamRedEyeOrb"]));
            }
            set {
                this["SpamRedEyeOrb"] = value;
            }
        }
    }
}
